@startuml

rectangle "Программирование" as pr
rectangle "Императивное" as imp
rectangle "Декларативное" as dek
rectangle "Структурное" as str
rectangle "Неструктурное" as nestr
rectangle "Объектно-ориентировнное" as oop
rectangle "Процедурное" as proc
rectangle "На основе классов" as cl
rectangle "Прототипное" as prototipe
rectangle "Декларативное" as dek
rectangle "Логическое" as log
rectangle "Функциональное" as func
rectangle "Апликативное" as app
rectangle "Комбинаторное" as komb

pr --> imp
pr --> dek
imp --> str
imp --> nestr
str --> oop
str --> proc
oop --> cl
oop --> prototipe
str ..> func
func --> app
func --> komb
dek --> log
dek --> func

@enduml
